# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: docker.io/wojciechmalotawojcik/go-ci:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: ~/zbackup
    steps:
      - checkout
      - run: echo $PATH
      - run: ./bin/zbackup dev/lint dev/test build
workflows:
  version: 2
  pull-request:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
